name: Close stale pull requests

on:
  push:
    branches: [ "master" ]



jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.REPO_TOKEN }}
          stale-pr-message: 'This PR has not been updated in the last 30 days. Closing it for now. Please reopen if needed.'
          days-before-pr-stale: 1
          days-before-pr-close: 0
          only-prs: true
