name: Close stale pull requests

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Close stale pull requests
        uses: peter-evans/close-pull-requests@v2
        with:
          days-before-stale: 0
          stale-pr-message: 'This PR has been automatically closed because it has not been merged within 30 days.'
          days-before-close: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
